<?php $randomPlayerList = rand(0, 10000); ?>
<?php $randomPlugins = rand(0, 10000); ?>
<?php echo $args['before_widget']; ?>
<?php echo $args['before_title'] . $instance['title'] . $args['after_title']; ?>
<p>
	<?php if (isset($instance['show_status']) && $instance['show_status'] == 'on'): ?>
		<?php echo esc_html__('Status', 'mcserverstatus'); ?>: <span style="color:red;font-weight:bold"><?php echo esc_html__('Offline', 'mcserverstatus'); ?></span><br>
	<?php endif; ?>

	<?php if (isset($instance['show_host']) && $instance['show_host'] == 'on'): ?>
		<?php echo esc_html__('Host', 'mcserverstatus'); ?>: <strong><?php echo $instance['host'], ':', $instance['port']; ?></strong><br>
	<?php endif; ?>

	<?php if (isset($instance['website']) && $instance['website']): ?>
		<a href="<?php echo $instance['website']; ?>" target="_blank"><?php echo esc_html__('Website', 'mcserverstatus'); ?></a><br>
	<?php endif; ?>

	<?php if (isset($instance['show_donate_info']) && $instance['show_donate_info']): ?>
		<font color="red"><?php echo esc_html__('Download this plugin:', 'mcserverstatus'); ?></font> <a href="https://wordpress.org/plugins/server-status-for-minecraft-pc-pe" target="_blank"><?php echo esc_html__('Server Status For Minecraft PC & PE', 'mcserverstatus'); ?></a><br>
		<font color="red"><?php echo esc_html__('Donate this plugin:', 'mcserverstatus'); ?></font> <a href="https://qr.allpay.com.tw/ffSH4" target="_blank"><?php echo esc_html__('allPay', 'mcserverstatus'); ?></a> | <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=42GN624D7ZLUN" target="_blank"><?php echo esc_html__('PayPal', 'mcserverstatus'); ?></a><br>
	<?php endif; ?>
</p>

<?php echo $args['after_widget']; ?>
